name: surfdock
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - numpy
  - scipy
  - pandas
  - openff-toolkit
  - openmm
  - openmmforcefields
  - pdbfixer
  - babel
  - biopandas
  - openbabel
  - plyfile
  - prody
  - torch-ema
  - torchmetrics
  - pytorch_geometric
  - pytorch_cluster
  - pytorch_scatter
  - pytorch_sparse
  - pytorch_spline_conv
  - spyrmsd
  - scikit-learn
  - accelerate
  - biopython
  - e3nn
  - huggingface_hub
  - mdanalysis
  - posebusters
  - rdkit
  - tokenizers
  - transformers
  - wandb
  - loguru
  - dimorphite-dl
  - fair-esm
  - mx::reduce
  - openbabel
  # - pip:
  #   - pymesh2@git+https://github.com/nuvolos-cloud/PyMesh
  #   - prefetch-generator


