name: surfdock
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - numpy
  - scipy
  - pandas
  - openff-toolkit
  - openmm
  - openmmforcefields
  - pdbfixer
  - babel
  - biopandas
  - openbabel
  - plyfile
  - prody
  - torch-ema
  - torchmetrics
  - pytorch_geometric
  - pytorch_cluster
  - pytorch_scatter
  - pytorch_sparse
  - pytorch_spline_conv
  - spyrmsd
  - scikit-learn
  - accelerate
  - biopython
  - e3nn
  - huggingface_hub
  - mdanalysis
  - posebusters
  - rdkit
  - tokenizers
  - transformers
  - wandb
  - loguru
  - dimorphite-dl
  - fair-esm
  - mx::reduce
  - openbabel
  - pip:
    - prefetch-generator
    # This needs to be installed from their release wheel file
    - https://github.com/nuvolos-cloud/PyMesh/releases/download/v0.3.1/pymesh2-0.3.1-cp310-cp310-linux_x86_64.whl


